# Generated by Django 3.0.2 on 2022-05-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_companylogo_menu_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.DeleteModel(
            name='CompanyLogo',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
